trigger:
  branches:
    include:
    - main
    exclude:
    - releases/*
    - features/*
  paths:
    include:
    - '*' # same as '/' for the repository root
    exclude:
    - 'deploy/*'
    - 'production/*'
    - 'scripts/*'
    - 'terraform/*'
    - 'docs/*' # same as 'docs/'
    - .gitignore

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: 'AcrBuildPush'
  displayName: 'Acr Build & Push'

  jobs:  
  - job: 'AcrBuildPush'
    displayName: 'Acr Build & Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: pipeline-templates/acr-build-push.yaml